### ISSUE TITLE
 Кнопка возврата на главную страницу

### ISSUE THREAD

**Issue by NeverGood** [IgnatKhodasevich/ghtBarApp#10]
Нету кнопки возврата на главную страницу из меню добавления бутылочек или списка юзеров

**Comment by NeverGood** [comment]
Поправка, из меню добавления бутылочки  такая кнопка есть

**Comment by NeverGood** [comment]
кнопки оказывается везде есть, но называються не очевидно, можно назвать Home

**Comment by IgnatKhodasevich** [comment]
Изменил
<img width="1186" alt="screen shot 2018-11-29 at 23 34 26" src="https://user-images.githubusercontent.com/18443219/49250288-82ce5280-f42f-11e8-9fdc-b6695730b2c7.png">
<img width="1186" alt="screen shot 2018-11-29 at 23 34 45" src="https://user-images.githubusercontent.com/18443219/49250289-82ce5280-f42f-11e8-8add-3e5340e21f43.png">
